ns-download-data blender;
ns-download-data sitcoms3d;
ns-download-data record3d;
ns-download-data dnerf;
ns-download-data phototourism;
ns-download-data sdfstudio;
ns-download-data nerfosr;
#ns-download-data nerfstudio --capture-name=bww_entrance;
#ns-download-data nerfstudio --capture-name=campanile; 
#ns-download-data nerfstudio --capture-name=desolation; 
#ns-download-data nerfstudio --capture-name=library; 
#ns-download-data nerfstudio --capture-name=redwoods2; 
#ns-download-data nerfstudio --capture-name=storefront; 
#ns-download-data nerfstudio --capture-name=vegetat; 
#ns-download-data nerfstudio --capture-name=ion; 
#ns-download-data nerfstudio --capture-name=Egypt; 
#ns-download-data nerfstudio --capture-name=person; 
#ns-download-data nerfstudio --capture-name=kitchen; 
#ns-download-data nerfstudio --capture-name=plane; 
#ns-download-data nerfstudio --capture-name=dozer; 
#ns-download-data nerfstudio --capture-name=floating-tree; 
#ns-download-data nerfstudio --capture-name=aspen; 
#ns-download-data nerfstudio --capture-name=stump; 
#ns-download-data nerfstudio --capture-name=sculpture; 
#ns-download-data nerfstudio --capture-name=Giannini-Hall; 
